# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup AL compiler
        uses: segesdk/setup-al@main
        with:
          version: 9.0.605172
          alternativeDownloadUrl: ${{secrets.ALTERNATIVEDOWNLOADURL }}
      # Runs a set of commands using the runners shell
      - name: Use AL compiler
        run: |
          $payload = "PATH=/d/a/setup-al/setup-al/alc/extension/bin/win32"
          $payload | write-host
          echo "sovs"
          env
          # echo $payload | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          "D:\a\setup-al\setup-al\alc\extension\bin\win32" >> $env:GITHUB_PATH
          env
          
          Write-Host "It worked!"
      - name: use alc
        run: |
          env
          alc.exe
